set nocompatible
syntax on
color default
set term=xterm-color

set t_Co=16
let &t_Co=16

let &t_Sf="\e[3%p1%dm"
let &t_Sb="\e[4%p1%dm"
let &t_AF="\e[3%p1%dm"
let &t_AB="\e[4%p1%dm"

set background=light
"let &background="light"

let g:html_no_progress = 1 
